config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :approvals, only: %i[index show] do
    member do
      put 'approve'
      put 'reject' 
    end
    collection do
      get 'filter'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users do
    member do
      get 'send_email_verification'
      get 'send_phone_verification'
      post 'verify_email_token'
      post 'verify_phone_token'
      get 'verification'
      get 'completed'
      get 'create_session'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index new create]
    end
  end
end

app/models/approval.rb
# frozen_string_literal: true

class Approval < ApplicationRecord
  belongs_to :user

  enum status: {
    started: 0,
    pending: 1,
    submitted: 2,
    approved: 3,
    rejected: 4
  }

  ransacker :id_to_s do
    Arel.sql("regexp_replace(to_char(\"#{table_name}\".\"id\", '9999999'), ' ', '', 'g')")
  end
end

app/controllers/approvals_controller.rb
# frozen_string_literal: true

class ApprovalsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = Approval.select('users.first_name, users.last_name, users.contact, users.dob, users.email, users.cnic, users.address, users.gender, approvals.id as id, approvals.status, approvals.updated_at').joins(:user).ransack(params[:q])

    @approvals = @q.result(distinct: true).order(id: :desc).page(params[:page]).per(9)
    # render json: @approvals
  end

  def show
    @approval = Approval.select('users.first_name, users.last_name, users.contact, users.dob, users.email, users.cnic, users.address, users.gender, approvals.id as id, approvals.status, approvals.updated_at').joins(:user).find(params[:id])
  end

  def approve
    @approval = Approval.find(params[:id])
    redirect_to approval_path if @approval.update(status: 3)
  end

  def reject
    @approval = Approval.find(params[:id])
    redirect_to approval_path if @approval.update(status: 4)
  end

  def filter
    filterd = params[:approval]
    
    criteria = { status_eq: filterd[:status], user_gender_eq: filterd[:gender], user_dob_gteq: Date.today.years_ago(filterd[:to].to_i+1), user_dob_lteq: Date.today.years_ago(filterd[:from].to_i) }.reject { |_, v| v.blank? }
    @q = Approval.select('users.first_name, users.last_name, users.contact, users.dob, users.email, users.cnic, users.address, users.gender, approvals.id as id, approvals.status, approvals.updated_at').joins(:user).ransack(criteria)

    @approvals = @q.result(distinct: true).order(id: :desc).page(params[:page]).per(9)
    render 'index'
  end



end

app/helpers/approvals_helper.rb
# frozen_string_literal: true

module ApprovalsHelper
  def get_status_class(status)
    case status
    when 'started'
      'bg-info bg-gradient'
    when 'pending'
      'bg-warning bg-gradient'
    when 'submitted'
      'bg-secondary bg-gradient'
    when 'approved'
      'bg-success bg-gradient'
    when 'rejected'
      'bg-danger bg-gradient'
    else
      'bg-dark bg-gradient'
    end
  end
end

app/views/approvals/index.html.erb
<%= render 'users/navbar' %>
<%= render 'layouts/alerts' %>
<div class="row mx-2">
    <div class="col-2 collapse" id="sidebar">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">
            <h4>Filter</h4>
            <hr>
            <ul class="nav">
                <li>  
                  <%= form_with(model: @approvals, url: filter_approvals_path, local: true, method: :get) do |f| %>
                    <%= f.label :age, "Age range:" %>
                    <br>
                    <div class="row mt-1">
                      <div class='col-3'><%= f.label :from, 'From:' %></div>
                      <div class='col'><%= f.text_field :from, value:"0", class:'form-control form-control-sm' %></div>
                    </div>
                    <div class="row mt-1">
                      <div class='col-3'><%= f.label :to, 'To:' %></div>
                      <div class='col'><%= f.text_field :to, value:"100", class:'form-control form-control-sm' %></div>
                    </div>
                    <hr>
                    <%= f.label :status, "Application status:" %>
                    <br>
                    <%= f.radio_button :status, "", class:'form-check-input', checked: true %> All
                    <br>
                    <%= f.radio_button :status, "1", class:'form-check-input' %> Pending
                    <br>
                    <%= f.radio_button :status, "2", class:'form-check-input' %> Completed
                    <br>
                    <%= f.radio_button :status, "3", class:'form-check-input' %> Approved
                    <br>
                    <%= f.radio_button :status, "4", class:'form-check-input' %> Rejected
                    <hr>
                    <%= f.label :gender, "Gender:" %>
                    <br>
                    <%= f.radio_button :gender, "", class:'form-check-input', checked: true %> All
                    <br>
                    <%= f.radio_button :gender, "Male", class:'form-check-input' %> Male&nbsp;
                    <%= f.radio_button :gender, "Female", class:'form-check-input' %> Female
                    <br>
                    <%= f.radio_button :gender, "Others", class:'form-check-input' %> Others
                    <hr>
                      <div class="d-flex justify-content-end"><%= f.submit "Search", class:'btn btn-sm btn-success' %></div>
                  <% end %>
                </li>
            </ul>
        </div>
    </div>
    <div class="col">
        <div class="card">
        <h3 class="card-header">Approval applications</h3>
            <div class="row m-1">
              <div class="col-6">
                <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="collapse" data-bs-target="#sidebar"><%= icon('fa-solid','filter') %>Filter</button>
              </div>
              <div class="d-flex justify-content-end col-6">
                  <%= search_form_for @q,url: approvals_path do |form| %>
                      <%#= form.search_field :status_eq, placeholder:'Search...', id:'bt-border-field' %>

                      <%= form.search_field :user_email_or_user_gender_or_user_first_name_or_user_last_name_or_user_cnic_or_user_address_or_user_contact_or_id_to_s_cont, placeholder:'Search...', id:'bt-border-field' %>
                      
                      <%= icon('fa-solid', 'search',class:'link-info')%>
                      <% form.submit "Search",class:' btn btn-sm btn-info' %>
                  <% end %>
              </div>
            </div>
            <table class="table table-striped" id="table">
                <thead id="tb-header">
                    <tr>
                    <th>Application#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Status</th>
                    <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    
                    <% @approvals.each do |approval| %>
                    <tr>
                        <td><%= approval.id %></td>
                        <td><%= approval.first_name.to_s+' '+approval.last_name.to_s %></td>
                        <td><%= approval.email %></td>
                        <td><%= approval.gender %></td>
                        <td><span id="tb-status" class = <%= get_status_class(approval.status) %> ><%= approval.status %><span></td>
                        <td><%= link_to 'view', approval ,class:'link-info'%></td>
                    </tr>
                    <% end %>
                </tbody>
                
            </table>
                <div class="d-flex justify-content-center">
                <%= paginate @approvals %>
                </div>
            <br>
        </div>
    </div>
</div>

app/views/approvals/show.html.erb
<%= render 'users/navbar' %>
<%= render 'layouts/alerts' %>
<div class="card m-5">
    <div class="card-header">
        <h4>Application#<%= @approval.id %></h4>
    </div>

    <div class="m-2">
        <h6>Status: <span id="status" class="<%= get_status_class(@approval.status) %>"><%= @approval.status %></span> <h6>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Application#:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.id %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Name:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.first_name.to_s+' '+@approval.last_name.to_s %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Email:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.email %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Contact#:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.contact %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>gender:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.gender %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>CNIC:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.cnic %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Date of birth:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.dob.nil? ? '' : format_date(@approval.dob) %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Age:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.dob.nil? ? '' : get_age(@approval.dob) %>
        </div>
    </div>

    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Address:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= @approval.address %>
        </div>
    </div>


    <div class="row px-5">
        <div class="col-md-4 col-sm-5">
            <strong>Submited on:</strong>
        </div>
        <div class="col-md-4 col-sm-5" id="bt-border-field">
            <%= format_date(@approval.updated_at) %>
        </div>
    </div>

    <% if @approval.status == 'approved' %>
    <div class="d-flex justify-content-end m-2">
        <nav>
            <%= link_to "Reject", reject_approval_path(@approval), method: :put, class:'btn btn-danger' %>
        </nav>
    </div>
    <% elsif @approval.status == 'rejected'%>
    <div class="d-flex justify-content-end m-2">
        <nav>
            <%= link_to "Approve", approve_approval_path(@approval),  method: :put, class:'btn btn-success' %>
        </nav>
    </div>
    <% else %>
    <div class="d-flex justify-content-end m-2">
        <nav>
            <%= link_to "Approve", approve_approval_path(@approval),  method: :put, class:'btn btn-success' %>
            <%= link_to "Reject", reject_approval_path(@approval), method: :put, class:'btn btn-danger' %>
        </nav>
    </div>
    <% end %>

</div>