config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :approvals, only: %i[index show] do
    member do
      put 'approve'
      put 'reject' 
    end
    collection do
      get 'filter'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users do
    member do
      get 'send_email_verification'
      get 'send_phone_verification'
      post 'verify_email_token'
      post 'verify_phone_token'
      get 'verification'
      get 'completed'
      get 'create_session'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index new create]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :approval,  dependent: :destroy
  has_one_attached :profile_picture
  has_one_attached :cnic_picture
  has_one_attached :dob_file
  has_one_attached :domicile_file

  # Include default devise modules. Others available are:
  # :lockable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, :confirmable

  validates :first_name, :cnic, :contact, :dob, :address, :gender, presence: true, on: :update
  validates :cnic, numericality: { only_integer: true }, on: :update
  validates :cnic, length: { is: 13 }, on: :update
  validates :cnic, uniqueness: true, on: :update
  validates :contact, phone: true, on: :update
  validate :must_be_valid_date, on: :update
  validates_presence_of :profile_picture, :cnic_picture, :dob_file, :domicile_file, on: :update
  validate :validate_files_content_type, on: :update

  after_create :notify_user

  def notify_user
    VerificationMailer.notify_to_complete_profile(self, self.password).deliver_now
  end

  def must_be_valid_date
    if dob.nil?
      errors.add(:dob, 'Date of Birth was not provided!')
    elsif dob >= Date.today
      errors.add(:dob, 'Invalid date of birth!(can not be in future)')
    end
  end

  def validate_files_content_type
    validate_img_content_type(profile_picture)
    validate_img_content_type(cnic_picture)
    validate_file_content_type(dob_file)
    validate_file_content_type(domicile_file)
  end

  def validate_img_content_type(element)
    return unless element.attached?
    allowed_content_types = ['image/png', 'image/jpeg', 'image/jpg','image/gif']
    unless allowed_content_types.include?(element.content_type)
      errors.add(:profile_and_cnic_picture, 'must be a PNG, JPEG, GIF, or JPG image')
    end
  end

  def validate_file_content_type(element)
    return unless element.attached?
    allowed_content_types = ['application/pdf', 'application/msword','application/vnd.oasis.opendocument.text', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/x-ole-storage']
    unless allowed_content_types.include?(element.content_type)
      errors.add(:birth_certificate_and_domicile_file, 'must be a PDF, DOC, ODT or DOCX file')
    end
  end

  enum role:
  {
    'non-supervisor': 0,
    supervisor: 1
  }
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::API

  def create
    if authenticate_admin_token and validate_content_type
      ProcessCsvFile.new(params[:csv_file]).execute
      render json: {status:'Background job is creating users...'}
    else
      render json: {status: 'file content type not supported!'}
    end    
  end

  private
    def validate_content_type
      params[:csv_file].content_type == 'text/csv'
    end

    def authenticate_admin_token
      request.headers[:authorization].split(' ')[1] == User.find_by(role:1).jwt_secret
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:create_session]
  before_action :set_user, except: [:create_session]
  before_action :set_tokenclient, except: %i[edit update]
  before_action :set_approval_application, only: %i[edit update verification completed check_existing_application]
  before_action :check_existing_application, only: %i[edit verification completed]

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Updated user successfully.'
      @approval_application.update(status: 1) unless %w[pending completed accepted
                                                        rejected].include?(@approval_application.status)
      redirect_to verification_user_path
    else
      redirect_to edit_user_path, alert: @user.errors.full_messages.to_sentence
    end
  end

  def send_email_verification
    @token = @tokenclient.generate_token

    return unless VerificationMailer.verify_email(@user, @token).deliver_now

    @tokenclient.set_email_token(@user)
    flash[:success] = 'Verfication code sent successfully.'
    redirect_back(fallback_location: verification_user_path)
  end

  def verify_email_token
    if params[:entry_email_token] == @user.email_verification_token.to_s and @user.email_token_expires_at >= Time.now
      @user.update(email_verified: true)
      flash[:success] = 'Email verified successfully.'
    else
      flash.alert = 'Incorrect or expired verification code!.'
    end
    redirect_back(fallback_location: verification_user_path)
  end

  def send_phone_verification
    @token = @tokenclient.generate_token
    return unless TwilioClient.new.send_text(@user,@token)
    #return unless true

    @tokenclient.set_contact_token(@user)
    flash[:success] = 'Verfication code sent successfully.'
    redirect_back(fallback_location: verification_user_path)
  end

  def verify_phone_token
    if params[:entry_number_token] == @user.contact_verification_token.to_s and @user.contact_token_expires_at >= Time.now
      @user.update(number_verified: true)
      flash[:success] = 'Phone number verified successfully.'
    else
      flash.alert = 'Incorrect or expired verification code!.'
    end
    redirect_back(fallback_location: verification_user_path)
  end

  def verification
    # verfication page
  end

  def completed
    # thankyou page
    @approval_application.update(status: 2) unless %w[submitted accepted
                                                      rejected].include?(@approval_application.status)
  end

  def create_session
    @user = User.find(params[:id])
    if !@user.nil?
      if JWT.decode(params[:token],"#{@user.id}our secret key")[0] == @user.email and @user.jwt_secret_expires_at.advance(days:3) >= Time.now
        flash[:success]='Signed in through email.'
        sign_in(@user)
        redirect_to edit_user_path
      else
        err = 'Invalid token or your link has expired...'
      render plain: err
      end
    else
      err = 'Invalid link: an error occurred during the search of record...'
      render plain: err
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :cnic, :contact, :dob, :address, :gender, :profile_picture,
                                 :cnic_picture, :dob_file, :domicile_file)
  end

  def set_user
    @user = current_user
  end

  def set_tokenclient
    @tokenclient = TokenClient.new
  end

  def set_approval_application
    @approval_application = Approval.where(user_id: current_user.id).first_or_initialize(status: 0)
    @approval_application.save
    @approval_application
  end

  def check_existing_application
    return unless %w[submitted accepted rejected].include?(@approval_application.status)

    flash.alert = 'You have already responded.'
    render :completed
  end

end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :first_name,'First name' %><br>
        <%= f.text_field :first_name, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :last_name,'Last name' %><br>
        <%= f.text_field :last_name, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :email,'email' %><br>
        <%= f.text_field :email, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :cnic,'CNIC' %><br>
        <%= f.text_field :cnic, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :contact,'Contact no.' %><br>
        <%= f.text_field :contact, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :dob,'Date of birth' %><br>
        <%= f.date_field :dob, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :address,'Address' %><br>
        <%= f.text_area :address, class:'form-control' %>
    </div>

    <div class="col-sm-12 col-md-6 p-2">
        <%= f.label :select_gender, "Select gender below" %><br><br>
        <div class="d-flex col-sm-8 col-md-6 justify-content-between">    
            <div>
                <%= f.radio_button :gender, "Male" %>
                <%= f.label :gender_male, "Male", class:"form-check-label" %>
            </div>
            <div>
                <%= f.radio_button :gender, "Female" %>
                <%= f.label :gender_female, "Female", class:"form-check-label" %>
            </div>
            <div>
                <%= f.radio_button :gender, "Others" %>
                <%= f.label :gender_others, "Others", class:"form-check-label" %>
            </div>
        </div>
    </div>
</div>

app/views/users/_navbar.html.erb
<div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%# expanded content %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          </li>
        </ul>
        <form class="d-flex">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %>
        </form>
      </div>
    </div>
  </nav>
</div>

app/views/users/_upload_document.html.erb
<div class="">
    <div class="">   
        
        <div class='row'>
            <div class="col-sm-12 col-md-2 p-2">
                <%= f.label :profile_picture,'Profile picture' %><br>
            </div>
            <div class="col-sm-12 col-md-6 p-2">
                <%= f.file_field :profile_picture, class:'form-control' %>
                <% if @user.profile_picture.attached? %>
                attached: <%= link_to @user.profile_picture.blob.filename, @user.profile_picture.blob, target: "_blank" %>
                <% end %>
                <small>(jpg,png,gif or jpeg)</small>
            </div>
        </div>
       

        <div class='row'>
            <div class="col-sm-12 col-md-2 p-2">
                <%= f.label :cnic_picture,'Picture of your CNIC' %><br>
            </div>
            <div class="col-sm-12 col-md-6 p-2">
                <%= f.file_field :cnic_picture, class:'form-control' %>
                <% if @user.cnic_picture.attached? %>
                attached: <%= link_to @user.cnic_picture.blob.filename, @user.cnic_picture.blob, target: "_blank" %>
                <% end %>
                <small>(jpg,png,gif or jpeg)</small>
            </div>
        </div>

        <div class='row'>
            <div class="col-sm-12 col-md-2 p-2">
                <%= f.label :dob_file,'Birth cretificate' %><br>
            </div>
            <div class="col-sm-12 col-md-6 p-2">
                <%= f.file_field :dob_file, class:'form-control' %>
                <% if @user.dob_file.attached? %>
                attached: <%= link_to @user.dob_file.blob.filename, @user.dob_file.blob, target: "_blank" %>
                <% end %>
                <small>(pdf,doc or docx)</small>
            </div>
        </div>

        <div class='row'>
            <div class="col-sm-12 col-md-2 p-2">
                <%= f.label :domicile_file,'Domicile certificate' %><br>
            </div>
            <div class="col-sm-12 col-md-6 p-2">
                <%= f.file_field :domicile_file, class:'form-control' %>
                <% if @user.domicile_file.attached? %>
                attached: <%= link_to @user.domicile_file.blob.filename, @user.domicile_file.blob, target: "_blank" %>
                <% end %>
                <small>(pdf,doc or docx)</small>
            </div>
        </div>
    </div>       
</div>

app/views/users/_verify_email_phone.html.erb
<div class="row">
    <div class="col-md-6 col-sm-12">
        
            <div class="mb-3">
                <label for="token_input" class="form-label">Verification code will be sent to your email</label>
                <div class="row">
                    <div class="col-8">
                        <input type="email" value="<%= user.email %>" class="form-control" disabled>
                    </div>
                    <% if !ActiveModel::Type::Boolean.new.cast(user.email_verified) %>
                    <div class="col-4">
                        <%= link_to "send code",send_email_verification_user_path, class:'btn btn-success' %>
                    </div>

                    <% else %>
                    <div class="col-4">
                        <label id='verified-tick'><%= icon('fa-solid', 'check', "Verified") %></label>
                    </div>
                    <% end %>

                </div><br>

                <% if !ActiveModel::Type::Boolean.new.cast(user.email_verified) %>
                    <%= form_with url: verify_phone_token_user_path, local: true do |form| %>

                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-3">
                            <%= form.label :entry_email_token, "Enter code" %>
                            </div>
                            <div class="col-3">
                                <%= form.text_field :entry_email_token, class:'form-control' %>
                            </div>
                            <div class="col-4">
                            <%= form.submit "Verify", class:'btn btn-info' %>
                            </div>
                        </div>
                        
                    <% end %>
                <% end %>
            </div>
        
    </div>

    <div class="col-md-6 col-sm-12">
        
            <div class="mb-3">
                <label for="token_input" class="form-label">Verification code will be sent number below</label>
                <div class="row">
                    <div class="col-8">
                        <input type="number" value="<%= user.contact %>" class="form-control" disabled>
                    </div>
                    <% if !ActiveModel::Type::Boolean.new.cast(user.number_verified) %>
                    <div class="col-4">
                        <%= link_to "send code",send_phone_verification_user_path, class:'btn btn-success' %>
                    </div>

                    <% else %>
                    <div class="col-4">
                        <label id='verified-tick'><%= icon('fa-solid', 'check', "Verified") %></label>
                    </div>
                    <% end %>

                </div><br>

                <% if !ActiveModel::Type::Boolean.new.cast(user.number_verified) %>
                    <%= form_with url: verify_phone_token_user_path, local: true do |form| %>

                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-3">
                            <%= form.label :entry_number_token, "Enter code" %>
                            </div>
                            <div class="col-3">
                                <%= form.text_field :entry_number_token, class:'form-control' %>
                            </div>
                            <div class="col-4">
                            <%= form.submit "Verify", class:'btn btn-info' %>
                            </div>
                        </div>
                        
                    <% end %>
                <% end %>
            </div>
        
    </div>
</div>

app/views/users/completed.html.erb
<%= render 'navbar' %>
<%= render 'layouts/alerts' %>
<div class="text-center" id="center-vertical">
    <h1 class="display-1">Thank You!</h1>
    
</div>

app/views/users/edit.html.erb
<%= render 'navbar' %>
<%= render 'layouts/alerts' %>
<div class="container">
    <div class=form>
        <%= form_with(model: @user, local: true) do |f| %>

        <!-- Basic information page -->
        <div id="page-1" class="card mt-4 p-5 bg-light">
            
            <%= render 'form', f: f %>
            <div class="d-flex justify-content-end mt-3">
                <a id="next_btn" class="btn btn-primary" onclick="goNext()">Next page</a>
            </div>
        </div>

        <!-- Upload document page -->
        <div id="page-2" class="d-none card mt-4 p-5 bg-light">
            <%= render 'upload_document',f: f %>

            <div class="row">
                <div class="col-6">
                    <a id="previous_btn" class="btn btn-primary" onclick="goBack()">Previous page</a>
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <%=f.submit "Submit", class:'btn btn-primary'%>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

<script>
    function goNext(){
        $("#page-2").removeClass('d-none')
        $("#page-1").addClass('d-none')
    }

    function goBack() {
        $("#page-1").removeClass('d-none')
        $("#page-2").addClass('d-none')
    }
</script>

app/views/users/verification.html.erb
<%= render 'navbar' %>
<%= render 'layouts/alerts' %>
<!-- Verify email and phone page -->


    <div class="card m-5 p-5 bg-light">
        <%= render 'verify_email_phone', user: @user %>
        <% if (@user.number_verified and @user.email_verified) %>
        <div class="row mt-5">
            <div class="col-6">
            </div>
            <div class="col-6 d-flex justify-content-end">
                <%=link_to "Complete Profile", completed_user_path, class:'btn btn-primary'%>
            </div>
        </div>
        <% end %>
    </div>